### ISSUE TITLE
Terraform Service Infrastructure - EC2  (Nat Instance)

### ISSUE THREAD

**Issue by tklusz** [CSUN-SeniorDesign/eat-infrastructure#26]

**Comment by AE637** [comment]
Created NAT instance with terraform. Still need to configure NAT with terraform via security group. We have talked about merging the NAT and bastion host into one instance.

**Comment by AE637** [comment]
Included new code that allocates elastic IP in NAT creation code, must test but holding off due to potential costs, either way we have already succesfully added elastic IP to an instance

**Comment by AE637** [comment]
NAT instance combined with bastion, all testing complete
