### ISSUE TITLE
Complete Documentation

### ISSUE THREAD

**Issue by AE637** [CSUN-SeniorDesign/eat-infrastructure#29]
Complete documentation of all tasks performed. Documentation must be clear, concise and complete as to not leave anything out. 

 
You should ​at least​ have the following documents in your infrastructure repository as a set of markdown files.  a. README.md for each repo giving basic information b. AWS setup c. AWS services setup (EC2, VPC, Route53, etc) d. AWS service diagram showing each aspect of the infrastructure e. How to write a blog post f. How to deploy a new blog post

**Comment by tklusz** [comment]
Service diagram is done

**Comment by tklusz** [comment]
See the "Documentation checklist" issue.
