### ISSUE TITLE
Task Breakdown for Project 2

### ISSUE THREAD

**Issue by h1ddengames** [CSUN-SeniorDesign/eat-infrastructure#73]
- [x] Project 2 @BriantheAvenger @koerk @AE637 @tklusz @h1ddengames (100 pts)
  - [x] Tasks @BriantheAvenger @koerk @AE637 @tklusz @h1ddengames (30 pts)
    - [x] Datadog Tasks @AE637 @BriantheAvenger @koerk
      - [x] DataDog Agent @AE637 @BriantheAvenger @koerk
        - [x] Track information
          - [x] CPU usage
          - [x] CPU load averages (1 minutes, 5 minute, 15 minute)
          - [x] Memory usage by the system
          - [x] Disk usage on the system
          - [x] Process uptime
          - [x] The number of requests to your website
          - [x] The latency for requests to your website
          - [x] Status codes of requests to your server (2xx, 3xx, 4xx, 5xx)

      - [x] DataDog Dashboard @AE637 @BriantheAvenger @koerk
        - [x] Create a dashboard in DataDog with the information above
        - [x] Create a graph with the success rate: 100 * ( 1 - ( 5xx requests / all requests))

    - [x] HashiCorp Packer @AE637 @BriantheAvenger @koerk
      - [x] Launch a new instance with a base AMI
      - [x] Create a new AMI from the launched instance
      - [x] Provide the AMI Id of the new base AMI
      - [x] Reference the AMI in ASG with a userdata script to download and install sites
      - [x] Install and configure any required services for this project
      - [x] Copy over a set of setup instructions using Ansible or another method

    - [x] CircleCI Tasks @h1ddengames @tklusz
      - [x] Setup
        - [x] Install hugo on the CI system with a simple download of the Linux version
      - [x] Build
        - [x] Run hugo against your blog to generate that the blog is successfully created
        - [x] Make sure that hugo was successfully run
      - [x] Package
        - [x] Get the SHA of the current commit in the blog git repo
        - [x] Create a tarball of your public folder contents with a filename of "<commit-sha>.tar.gz"
      - [x] Upload
        - [x] Push the tarball up to Amazon S3 to a designated location, using a restricted set of
  credentials provided to CircleCI
        - [x] Update something to tell the instances that there is a new version available in the
  location they are setup to watch - This will probably be done with a chronjob.

    - [x] AWS @h1ddengames @tklusz
      - [x] AWS IAM @tklusz
        - [x] IAM user with privileges for the PUT action
        - [x] create a policy with the GET action

      - [x] AWS ASG @tklusz
        - [x] Launch configuration
        - [x] ASG

      - [x] AWS S3 @h1ddengames @BriantheAvenger 
        - [x] Create a bucket
        - [x] Store packaged website
        - [x] Track packages over time
        - [x] Find the latest version built
        - [x] Pull down new code

      - [x] AWS Route53 @h1ddengames
        - [x] Add the staging subdomain to Route53
        - [x] Task 2

    - [x] Deploy Websites @BriantheAvenger @koerk @AE637 @tklusz @h1ddengames
      - [x] Check S3 for the latest build ID
      - [x] Check the latest build on the local system
      - [x] If newer version is available, download and unpackage somewhere on the system
      - [x] Point the webserver at the new version of the code
      - [x] Gracefully restart the web server to make sure it is serving the new information
      - [x] Clean up an packages or deployments that are no longer needed
      - [x] A special location or value should be updated to signal that a new deployment is required
      - [x] Stagger the runtimes of the cronjobs on the instances

    - [x] Webserver Configuration @BriantheAvenger @koerk @AE637 @tklusz @h1ddengames
      - [x] Task 1
      - [x] Task 2

======================================================================

  - [x] Deliverables @BriantheAvenger @koerk @AE637 @tklusz @h1ddengames
    - [x] Completed above tasks

    - [x] Two running websites

    - [x] Blog Post 5 (10 pts)
      - [x] @BriantheAvenger
      - [x] @koerk
      - [x] @AE637
      - [x] @tklusz
      - [x] @h1ddengames

    - [x] Blog Post 6 (10 pts)
      - [x] @BriantheAvenger
      - [x] @koerk
      - [x] @AE637
      - [x] @tklusz
      - [x] @h1ddengames

    - [x] Documentation (30 pts)
      - [x] README.md for each repo giving basic information
      - [x] AWS Setup
      - [x] AWS services setup
        - [x] EC2
        - [x] VPC
        - [x] Route53
      - [x] AWS service diagram
      - [x] How to write a blog post
      - [x] How to deploy a new blog post

    - [x] Automation using Terraform, Ansible, Packer, Scripts, Configurations
      - [x] Terraform
      - [x] Ansible
      - [x] Packer
      - [x] Scripts
      - [x] Configurations

    - [x] Group presentation @BriantheAvenger @koerk @AE637 @tklusz @h1ddengames (20 pts)
      - [x] @BriantheAvenger
      - [x] @koerk
      - [x] @AE637
      - [x] @tklusz
      - [x] @h1ddengames

- [ ] **Bonus:** Add titles to our website blogs (so we can click on them) also improve blog theme, unless we get points off for it Project 1, then this becomes an actual task. If we are going to do this, update the theme config manually then push it back up to github.

**Comment by tklusz** [comment]
Hugo installed with CircleCI using snapd. See [here.](https://github.com/CSUN-SeniorDesign/eat-blog/commit/32f369d4dc3e8fb960a79bd150c2399dcce86e6d)

**Comment by tklusz** [comment]
CircleCI Build and Package sections are done.

**Comment by tklusz** [comment]
CircleCI is basically done. Should update terraform permissions for the IAM users, but not sure how to specify a sub-policy in Terraform.

**Comment by tklusz** [comment]
Updated S3 user to have minimal permissions.

**Comment by tklusz** [comment]
Both IAM users are done. If there is a problem getting from the bucket, take a look at them again because they might not be 100% correct (The instance getter at least)

**Comment by tklusz** [comment]
Datadog needs to have the instances up and running before it can be finished, users on datadog were moved to packer.

**Comment by tklusz** [comment]
S3 needs to get pulled down, which requires permissions. These can be set with an IAM role assigned to the asg, which is giving an error in terraform. Will try again later.

**Comment by tklusz** [comment]
IAM role has been set and its now possible to pull from S3.

**Comment by tklusz** [comment]
Packer is still being configured, primarily by Erik, although Brian, Shahid and Alex are helping him. 

- We need both cronjobs done with scripts completed for them. 
- Datadog agent still needs to be installed. 
- Apache2 virtual sites need to be set up. 
- Documentation, blogs, and presentation all needs to be finished .

**Comment by tklusz** [comment]
Created python script to update the ProductionSite.txt file on the blog repo. Everything is still being done through GitHub. There is an interesting workaround so the script doesn't need aws cli, it just uploads to GitHub using a branch, commit and push. CircleCI takes care of uploading from GitHub to s3.

This still needs to be pulled with the script for the cronjob.

**Comment by h1ddengames** [comment]
Group presentation finished.

**Comment by tklusz** [comment]
Don't have clickable titles, but changed the blog theme. Click the two orange >> to read the full blog post, untll we update titles.
