### ISSUE TITLE
ECS

### ISSUE THREAD

**Issue by tklusz** [CSUN-SeniorDesign/eat-infrastructure#91]
We will be using AWS ECS
to run our blogs instead of using EC2 instances directly.. It is up to you how you provide
resources to the cluster, but you'll need to setup a new cluster that is easily scalable for the
required amount of resources for services or tasks. You should not need to login to set the
resources for the cluster

ECS gives us a cluster where we define a set of resources that our service needs and moves us
away from manually placing applications on the required number of hosts. The ECS cluster and
agent will take care of running services on hosts with enough resources

You will need to setup a service in ECS to run your blog using the container images created.
This service should have the ability to automatically scale based on some criteria (e.g. CPU
usage, number of requests to the ALB, etc). The ECS service should also automatically register
to and deregister from the ALB.

**Comment by ErikBlomquist** [comment]
ECS works properly
